# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('internal_identification_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('margh', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=50)),
                ('barga_fit', models.CharField(max_length=100)),
                ('land_kitta_number', models.CharField(max_length=100)),
                ('land_area', models.CharField(max_length=100)),
                ('monthly_fee', models.IntegerField()),
            ],
        ),
    ]
