# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '\u0917\u094d\u0930\u093e\u0939\u0915 \u092c\u093f\u0935\u0930\u0923', 'verbose_name_plural': '\u0917\u094d\u0930\u093e\u0939\u0915 \u092c\u093f\u0935\u0930\u0923'},
        ),
        migrations.AddField(
            model_name='customer',
            name='chetra',
            field=models.CharField(choices=[(b'awasiya', '\u0906\u0935\u093e\u0938\u0940\u092f'), (b'angsik_bajar', '\u0905\u0928\u094d\u0917\u094d\u0938\u093f\u0915 \u092c\u091c\u093e\u0930'), (b'bajar', '\u092c\u091c\u093e\u0930'), (b'mukhya_bajar', '\u092e\u0941\u0916\u094d\u092f \u092c\u091c\u093e\u0930')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=250, verbose_name='\u0920\u0947\u0917\u093e\u0928\u093e'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='barga_fit',
            field=models.CharField(max_length=100, verbose_name='\u0935\u0930\u094d\u0917 \u092b\u093f\u091f'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='house_no',
            field=models.CharField(max_length=50, verbose_name='\u0918\u0930 \u0928.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land_area',
            field=models.CharField(max_length=100, verbose_name='\u091c\u0917\u094d\u0917\u093e\u0915\u094b \u091a\u0947\u0924\u094d\u0930\u092b\u0932'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land_kitta_number',
            field=models.CharField(max_length=100, verbose_name='\u091c\u0917\u094d\u0917\u093e \u0915\u093f. \u0928.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='margh',
            field=models.CharField(max_length=100, verbose_name='\u092e\u093e\u0930\u094d\u0917'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_fee',
            field=models.IntegerField(verbose_name='\u092e\u093e\u0938\u093f\u0915 \u0938\u0941\u0932\u094d\u0915'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u0928\u093e\u092e'),
        ),
    ]
