# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170218_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='\u0930\u0915\u092e')),
                ('remarks', models.CharField(max_length=300, verbose_name='\u091f\u093f\u092a\u094d\u092a\u0923\u0940')),
            ],
            options={
                'verbose_name': '\u092d\u0941\u0915\u094d\u0924\u093e\u0928\u0940',
                'verbose_name_plural': '\u092d\u0941\u0915\u094d\u0924\u093e\u0928\u0940',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='payments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Payments'),
        ),
    ]
