# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170218_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Payments'),
        ),
    ]
