# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170218_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payments',
        ),
        migrations.AddField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
        migrations.AddField(
            model_name='payments',
            name='rasid_number',
            field=models.IntegerField(null=True, verbose_name='\u0930\u0938\u093f\u0926 \u0928.'),
        ),
    ]
