# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('internal_identification_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='\u0928\u093e\u092e')),
                ('address', models.CharField(max_length=250, verbose_name='\u0920\u0947\u0917\u093e\u0928\u093e')),
                ('margh', models.CharField(max_length=100, verbose_name='\u092e\u093e\u0930\u094d\u0917')),
                ('house_no', models.CharField(max_length=50, verbose_name='\u0918\u0930 \u0928.')),
                ('barga_fit', models.CharField(max_length=100, verbose_name='\u0935\u0930\u094d\u0917 \u092b\u093f\u091f')),
                ('land_kitta_number', models.CharField(max_length=100, verbose_name='\u091c\u0917\u094d\u0917\u093e \u0915\u093f. \u0928.')),
                ('land_area', models.CharField(max_length=100, verbose_name='\u091c\u0917\u094d\u0917\u093e\u0915\u094b \u091a\u0947\u0924\u094d\u0930\u092b\u0932')),
                ('monthly_fee', models.IntegerField(verbose_name='\u092e\u093e\u0938\u093f\u0915 \u0938\u0941\u0932\u094d\u0915')),
                ('chetra', models.CharField(choices=[(b'awasiya', '\u0906\u0935\u093e\u0938\u0940\u092f'), (b'angsik_bajar', '\u0905\u0928\u094d\u0917\u094d\u0938\u093f\u0915 \u092c\u091c\u093e\u0930'), (b'bajar', '\u092c\u091c\u093e\u0930'), (b'mukhya_bajar', '\u092e\u0941\u0916\u094d\u092f \u092c\u091c\u093e\u0930')], default=None, max_length=100, verbose_name=b'\xe0\xa4\x95\xe0\xa5\x8d\xe0\xa4\xb7\xe0\xa5\x87\xe0\xa4\xa4\xe0\xa5\x8d\xe0\xa4\xb0 ')),
                ('batoko_kisim', models.CharField(choices=[(b'kacchi', '\u0915\u091a\u094d\u091a\u0940'), (b'sahayek', '\u0938\u093e\u0939\u092f\u0947\u0915'), (b'pichbato', '\u092a\u0940\u091a\u092c\u093e\u091f\u094b'), (b'mukhya_pichbato', '\u092e\u0941\u0916\u094d\u092f \u092a\u093f\u091a\u092c\u093e\u091f\u094b')], default=None, max_length=100, verbose_name=b'\xe0\xa4\xac\xe0\xa4\xbe\xe0\xa4\x9f\xe0\xa5\x8b \xe0\xa4\x95\xe0\xa5\x8b \xe0\xa4\x95\xe0\xa4\xbf\xe0\xa4\xb8\xe0\xa4\xbf\xe0\xa4\xae')),
                ('ghar_ko_kisim', models.CharField(choices=[(b'kacchi', '\u0915\u091a\u094d\u091a\u0940'), (b'pakki', '\u092a\u0915\u094d\u0915\u093f')], default=None, max_length=100, verbose_name=b'\xe0\xa4\x98\xe0\xa4\xb0 \xe0\xa4\x95\xe0\xa5\x8b \xe0\xa4\x95\xe0\xa4\xbf\xe0\xa4\xb8\xe0\xa4\xbf\xe0\xa4\xae')),
            ],
            options={
                'verbose_name': '\u0917\u094d\u0930\u093e\u0939\u0915 \u092c\u093f\u0935\u0930\u0923',
                'verbose_name_plural': '\u0917\u094d\u0930\u093e\u0939\u0915 \u092c\u093f\u0935\u0930\u0923',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasid_number', models.IntegerField(null=True, verbose_name='\u0930\u0938\u093f\u0926 \u0928.')),
                ('amount', models.IntegerField(verbose_name='\u0930\u0915\u092e')),
                ('remarks', models.CharField(max_length=300, verbose_name='\u091f\u093f\u092a\u094d\u092a\u0923\u0940')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'verbose_name': '\u092d\u0941\u0915\u094d\u0924\u093e\u0928\u0940',
                'verbose_name_plural': '\u092d\u0941\u0915\u094d\u0924\u093e\u0928\u0940',
            },
        ),
    ]
